apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeinApp
  namespace: app-ns
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeinApp
  template:
    metadata:
      labels:
        app: zeinApp
    spec:
      containers:
        - name: zeinApp
          image: docker.io/zeinsss/finalapp
          ports:
            - containerPort: 3000
